### ISSUE TITLE
Bootloop

### ISSUE THREAD

**Issue by nanitheheck** [ShaDisNX255/NcX_Stock#6]
When I install the firmware with all the files needed when i boot into the system, it bootloops. Any help?

**Comment by ShaDisNX255** [comment]
Literally impossible for me to know what's wrong without logs. Just follow the instructions in the XDA thread, it worked for me and hundreds of other people and if you're still having problems then you may need to research how to provide logs otherwise I can't possibly know what's wrong with the installation.
